# NumPy
***
## Basics
***

In [1]:
import numpy as np

In [2]:
#generating basic array in numpy
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [9]:
#generating an array of 0s
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [4]:
#generating an empty array (generates random numbers based on memory state to increase efficiency)
a = np.empty(4)
print(a)

[2.12199579e-314 0.00000000e+000 1.75887370e-321 6.95293141e-310]


In [5]:
#generating ordered list of numbers
a = np.arange(5)
print(a)

#arranging numbers 2 - 9 (not including 9) but only every second number
a = np.arange(2, 9, 2)
print(a)

[0 1 2 3 4]
[2 4 6 8]


In [6]:
#generating list of numbers from 0 to 10 in intervals of 3
a = np.linspace(0, 10, num=3)
print(a)

[ 0.  5. 10.]


In [11]:
#generate array of ones but specify the data type to int since the default is float
a = np.ones(2)
print(a)
a = np.ones(2, dtype=np.int64)
print(a)

[1. 1.]
[1 1]


  ## Adding, removing, and sorting elements
  ***

In [12]:
myArray = np.array([2, 6, 7, 4, 1, 0, 25, 6, 12])

In [45]:
#sort in ascending order
np.sort(myArray)

array([ 0,  1,  2,  4,  6,  6,  7, 12, 25])

In [47]:
#sort in descending order
np.sort(myArray)[::-1]

array([25, 12,  7,  6,  6,  4,  2,  1,  0])

In [56]:
a = np.array([1, 2, 3 ,4])
b = np.array([5, 6, 7, 8])

#Adding two arrays together
c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6 7 8]
[ 5  6  7 12]
